name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
          - runner: macos-latest
            target: x86_64-apple-darwin

    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: cargo run --package tool-dev -- init
    - name: Check
      run: cargo run --package tool-dev -- check
    - name: Clippy
      run: cargo run --package tool-dev -- clippy
    - name: Format
      run: cargo run --package tool-dev -- fmt
    - name: Test
      run: cargo run --package tool-dev -- test --target ${{ matrix.target }}
